blank_issues_enabled: true
contact_links:
  - name: Want to ask questions about the project?
    url: https://github.com/termux-play-store/termux-issues/discussions
    about: Join GitHub Discussions
